
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 19 18:16:06 CET 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class LexerSymbol {
  /* terminals */
  public static final int STRING_LITERAL = 53;
  public static final int MULT = 16;
  public static final int CHAR = 13;
  public static final int GE = 38;
  public static final int LACC = 4;
  public static final int FCT = 27;
  public static final int GREAT = 34;
  public static final int SEMIC = 14;
  public static final int INTEGER = 9;
  public static final int REPEAT = 26;
  public static final int LESS = 33;
  public static final int MINUS = 30;
  public static final int CHAPEAU = 8;
  public static final int NOT = 43;
  public static final int RCRO = 7;
  public static final int RPAR = 3;
  public static final int TYPE = 45;
  public static final int IN = 39;
  public static final int COMMA = 48;
  public static final int BOOL = 12;
  public static final int CLASS = 40;
  public static final int DIV = 31;
  public static final int OR_OP = 42;
  public static final int PLUS = 15;
  public static final int IF = 22;
  public static final int ID = 52;
  public static final int AND_OP = 41;
  public static final int LE = 37;
  public static final int OF = 17;
  public static final int EOF = 0;
  public static final int RETURN = 29;
  public static final int EQUAL = 35;
  public static final int TRUE = 18;
  public static final int error = 1;
  public static final int RACC = 5;
  public static final int NULL = 20;
  public static final int MOD = 32;
  public static final int REAL = 49;
  public static final int COLON = 46;
  public static final int FOREACH = 25;
  public static final int ELSE = 23;
  public static final int LETTER = 54;
  public static final int POINT = 47;
  public static final int WHILE = 24;
  public static final int LIST = 51;
  public static final int FLOAT = 10;
  public static final int NB = 50;
  public static final int LCRO = 6;
  public static final int LPAR = 2;
  public static final int STRING = 11;
  public static final int DIFF = 36;
  public static final int AFF = 44;
  public static final int FALSE = 19;
  public static final int STRUCT = 21;
  public static final int PROCEDURE = 28;
}

